version: '3'
services: 
  redis-server:
    image: redis:5-alpine3.8
  mongo:
    image: mvertes/alpine-mongo:4.0.3-0
    volumes:
      - "mongoData:/data/mongo/db"
  lotto-live-api:
    restart: always
    image: mrsmith9ja/lotto-live-api
    environment:
      -  APP_ID=abcd
      -  MASTER_KEY=efg
      -  SERVER_URL=localhost
      -  redisURL=redis-server:6379
      -  PORT=3030
    ports: 
      - "3030:3030"
  lotto-api:
    image: mrsmith9ja/lotto-main-api
    environment: 
      -  DB_HOST=mongo:27017
      -  DB_NAME=lotto
      -  APP_ID=abcd
      -  MASTER_KEY=efg
      -  HOST_NAME=localhost
      -  redisURL=redis-server:6379
      -  PARSE_MOUNT=api
      -  PROD=false
    ports: 
      - "3000:3000"
    depends_on: 
      - mongo
  lotto-user-front:
    image: mrsmith9ja/lotto-user-ui
    ports: 
      - "8080:80"
volumes:
  mongoData: