apiVersion: apps/v1
kind: Deployment
metadata:
  name: lotto-live-api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: live-server
  template:
    metadata:
      labels:
        component: live-server
    spec:
      containers:
      - name: live-query-server
        image: mrsmith9ja/lotto-live-api
        env:
          - name: APP_ID
            value: "abcd"
          - name: redisURL
            value: live-query-redis-cluster-ip-service
          - name: redisPort
            value: "6379"
          - name: MASTER_KEY
            valueFrom:
              secretKeyRef:
                name: lottomasterkey
                key: MASTER_KEY
          - name: PORT
            value: "3030"
        ports:
          - containerPort: 3030
        resources:
          requests:
            cpu: "250m"
            memory: "64Mi"
          limits:
            memory: "64Mi"
            cpu: "250m"
